apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gitops-agent
  namespace: default
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: main
              image: alpine:latest
              imagePullPolicy: IfNotPresent
              args:
                - /bin/sh
                - -c
                - git clone https://github.com/alexec/gitops-workshop && kubectl apply -R -f gitops-workshop/poor-mans-gitops/apps
          restartPolicy: Never
